import ArmsIcon from '@/Components/ArmsIcon';
import { useEffect, useState } from 'react';

type Person = { id:number; name:string; email?:string|null; position?:string|null } | null;
type Activity = { id:number; event:string; description:string; created_at?:string|null; actor:Person };
type Access = { user:Person; role:string; department?:string|null; source:string; can_download:boolean; can_upload:boolean };
type Info = { kind:'folder'|'document'; name:string; type:string; mime_type?:string|null; size?:number|null; description?:string|null; path:string[]; created_at?:string|null; created_by:Person; uploaded_by?:Person; updated_at?:string|null; modified_by:Person; status?:string|null; version?:number|null; children_count?:number|null; documents_count?:number|null; preview_url?:string|null; activity:Activity[]; access:Access[] };

const when = (value?:string|null) => value ? new Intl.DateTimeFormat('en-PH',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value)) : '—';
const size = (bytes?:number|null) => { if (!bytes) return '—'; const units=['B','KB','MB','GB']; let value=bytes, unit=0; while(value>=1024&&unit<units.length-1){value/=1024;unit++;} return `${value.toFixed(unit ? 1 : 0)} ${units[unit]}`; };
const eventLabel = (event:string) => event.split('.').map((part)=>part.charAt(0).toUpperCase()+part.slice(1)).join(' ');

export default function InformationDrawer({ target, onClose }:{ target:{name:string;url:string;kind:'folder'|'document'}|null; onClose:()=>void }) {
    const [tab,setTab]=useState<'details'|'activity'|'access'>('details');
    const [data,setData]=useState<Info|null>(null);
    const [error,setError]=useState('');
    useEffect(()=>{ if(!target)return; setData(null); setError(''); setTab('details'); const controller=new AbortController(); fetch(target.url,{headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'},credentials:'same-origin',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error(r.status===403?'You no longer have access to this item.':'Unable to load information.'); return r.json();}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)}); return()=>controller.abort(); },[target]);
    if(!target)return null;
    return <aside className="fixed inset-y-0 right-0 z-[95] flex w-full max-w-[430px] flex-col border-l border-stone-200 bg-white shadow-2xl sm:top-0">
        <header className="flex h-14 items-center justify-between border-b border-stone-200 px-5"><h2 className="flex items-center gap-2 text-base font-semibold text-stone-900"><span className="grid h-6 w-6 place-items-center rounded-full border border-stone-500 text-xs">i</span>Information</h2><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full text-2xl text-stone-600 hover:bg-stone-100" aria-label="Close information">×</button></header>
        <div className="border-b border-stone-200 px-6 py-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-emerald-50 text-arms-green"><ArmsIcon name={target.kind==='folder'?'folder':'document'} className="h-6 w-6" /></span><div className="min-w-0"><p className="break-words font-semibold text-stone-900">{data?.name||target.name}</p><p className="text-xs text-stone-500">{data ? `${data.type}${data.size ? ` • ${size(data.size)}`:''}` : 'Loading information...'}</p></div></div></div>
        <nav className="grid grid-cols-3 border-b border-stone-200">{(['details','activity','access'] as const).map(item=><button key={item} onClick={()=>setTab(item)} className={'border-b-2 px-3 py-3 text-sm font-medium capitalize '+(tab===item?'border-arms-green text-arms-green':'border-transparent text-stone-600 hover:bg-stone-50')}>{item}</button>)}</nav>
        <div className="min-h-0 flex-1 overflow-y-auto px-6 py-5">{error?<div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>:!data?<div className="py-12 text-center text-sm text-stone-500">Loading details...</div>:tab==='details'?<Details data={data}/>:tab==='activity'?<ActivityTab items={data.activity}/>:<AccessTab items={data.access}/>}</div>
    </aside>;
}

function Details({data}:{data:Info}) { return <div className="space-y-6">{data.kind==='document'&&data.preview_url&&<div className="h-44 overflow-hidden rounded-xl border border-stone-200 bg-stone-50"><iframe title={'Preview '+data.name} src={data.preview_url} className="pointer-events-none h-full w-full border-0 bg-white" /></div>}{data.description&&<section><h3 className="text-sm font-semibold text-stone-900">Description</h3><p className="mt-1 whitespace-pre-wrap text-sm leading-5 text-stone-600">{data.description}</p></section>}<section><h3 className="mb-3 text-sm font-semibold text-stone-900">Details</h3><dl className="grid grid-cols-[105px_1fr] gap-x-3 gap-y-3 text-sm"><dt className="text-stone-500">Type</dt><dd>{data.type}</dd>{data.kind==='document'&&<><dt className="text-stone-500">Size</dt><dd>{size(data.size)}</dd></>}<dt className="text-stone-500">Location</dt><dd className="min-w-0">{data.path.map((part,index)=><span key={index} className="inline break-words text-stone-700">{index>0&&<span className="px-1 text-stone-400">›</span>}{part}</span>)}</dd><dt className="text-stone-500">Created</dt><dd>{when(data.created_at)}</dd><dt className="text-stone-500">Created by</dt><dd><PersonLine person={data.created_by}/></dd>{data.uploaded_by&&<><dt className="text-stone-500">Uploaded by</dt><dd><PersonLine person={data.uploaded_by}/></dd></>}<dt className="text-stone-500">Last modified</dt><dd>{when(data.updated_at)}</dd><dt className="text-stone-500">Modified by</dt><dd><PersonLine person={data.modified_by}/></dd>{data.status&&<><dt className="text-stone-500">Status</dt><dd>{data.status}</dd></>}{data.kind==='folder'&&<><dt className="text-stone-500">Subfolders</dt><dd>{data.children_count??0}</dd><dt className="text-stone-500">Documents</dt><dd>{data.documents_count??0}</dd></>}</dl></section></div> }
function ActivityTab({items}:{items:Activity[]}) { if(!items.length)return <Empty title="No recorded activity" text="Only real ARMS audit events are shown here."/>; return <div><h3 className="mb-4 text-sm font-semibold text-stone-900">Activity</h3><div className="space-y-5">{items.map(item=><article key={item.id} className="flex gap-3"><Avatar person={item.actor}/><div className="min-w-0"><p className="text-sm font-semibold text-stone-900">{item.actor?.name||'System'}</p><p className="mt-0.5 break-words text-sm leading-5 text-stone-600">{item.description||eventLabel(item.event)}</p><p className="mt-1 text-xs text-stone-400">{when(item.created_at)}</p></div></article>)}</div></div> }
function AccessTab({items}:{items:Access[]}) { if(!items.length)return <Empty title="No direct access assignments" text="Higher-level role access may still apply through the existing ARMS authorization rules."/>; return <div><h3 className="mb-4 text-base font-semibold text-stone-900">Who has access</h3><div className="space-y-4">{items.map((item,index)=><article key={`${item.user?.id}-${item.source}-${index}`} className="flex gap-3"><Avatar person={item.user}/><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-stone-900">{item.user?.name}</p><p className="break-words text-xs text-stone-500">{item.user?.email}</p><p className="mt-1 text-xs text-arms-green">{item.source}{item.department?` • ${item.department}`:''}</p></div><span className="text-xs text-stone-500">{item.can_upload?'Uploader':item.can_download?'Viewer + download':'Viewer'}</span></article>)}</div></div> }
function PersonLine({person}:{person:Person}) { return person?<span><span className="font-medium text-stone-800">{person.name}</span>{person.email&&<span className="block break-all text-xs text-stone-500">{person.email}</span>}</span>:<span>—</span> }
function Avatar({person}:{person:Person}) { return <span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-emerald-100 text-xs font-bold text-arms-green">{person?.name?.split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase()||'S'}</span> }
function Empty({title,text}:{title:string;text:string}) { return <div className="py-12 text-center"><p className="font-semibold text-stone-700">{title}</p><p className="mx-auto mt-1 max-w-xs text-sm text-stone-500">{text}</p></div> }
